# docker/nginx/conf.d/production.conf

server {
    listen 80;
    server_name sellmyhouse.sg www.sellmyhouse.sg;

    location /.well-known/acme-challenge/ {
        root /var/www/certbot;
    }
    location / {
        return 301 https://sellmyhouse.sg$request_uri;
    }
}

server {
    listen 443 ssl;
    server_name sellmyhouse.sg www.sellmyhouse.sg;

    ssl_certificate     /etc/letsencrypt/live/sellmyhouse.sg/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/sellmyhouse.sg/privkey.pem;
    ssl_protocols       TLSv1.2 TLSv1.3;
    ssl_ciphers         HIGH:!aNULL:!MD5;

    client_max_body_size 15M;

    location / {
        proxy_pass         http://app-prod:3000;
        proxy_http_version 1.1;
        proxy_set_header   Host              $host;
        proxy_set_header   X-Real-IP         $remote_addr;
        proxy_set_header   X-Forwarded-For   $proxy_add_x_forwarded_for;
        proxy_set_header   X-Forwarded-Proto $scheme;
        proxy_set_header   Upgrade           $http_upgrade;
        proxy_set_header   Connection        'upgrade';
        proxy_read_timeout 60s;
    }
}
