# docker/docker-compose.production.yml
services:
  app-prod:
    image: ghcr.io/duckchief/sellmyhouse:latest
    container_name: app-prod
    expose:
      - "3000"
    env_file:
      - /opt/sellmyhouse/production/.env
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - uploads:/app/uploads
      - /var/run/clamav/clamd.ctl:/var/run/clamav/clamd.ctl:ro
    restart: unless-stopped
    networks:
      - smh_net
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "5"

networks:
  smh_net:
    external: true

volumes:
  uploads:
